// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3824.HolonomicRobot.subsystems;

import org.usfirst.frc3824.HolonomicRobot.RobotMap;
import org.usfirst.frc3824.HolonomicRobot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class DriveBase extends Subsystem
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    SpeedController frontLeftMotor = RobotMap.driveBasefrontLeftMotor;
    SpeedController rearLeftMotor = RobotMap.driveBaserearLeftMotor;
    SpeedController frontRightMotor = RobotMap.driveBasefrontRightMotor;
    SpeedController rearRightMotor = RobotMap.driveBaserearRightMotor;
    RobotDrive robotDrive = RobotMap.driveBaseRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveOffJoystick());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    public void driveWithJoystick(Joystick stick)
    {
        robotDrive.mecanumDrive_Polar(stick.getMagnitude() / 2.0f, stick.getDirectionDegrees(), stick.getTwist() / 2.0f);
    }
}
