// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3824.HolonomicRobot;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static SpeedController driveBasefrontLeftMotor;
    public static SpeedController driveBaserearLeftMotor;
    public static SpeedController driveBasefrontRightMotor;
    public static SpeedController driveBaserearRightMotor;
    public static RobotDrive driveBaseRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBasefrontLeftMotor = new Victor(1, 1);

        driveBaserearLeftMotor = new Victor(1, 2);

        driveBasefrontRightMotor = new Victor(1, 3);

        driveBaserearRightMotor = new Victor(1, 4);

        driveBaseRobotDrive = new RobotDrive(driveBasefrontLeftMotor, driveBaserearLeftMotor,
                driveBasefrontRightMotor, driveBaserearRightMotor);

        driveBaseRobotDrive.setSafetyEnabled(false);
        driveBaseRobotDrive.setExpiration(0.1);
        driveBaseRobotDrive.setSensitivity(0.5);
        driveBaseRobotDrive.setMaxOutput(1.0);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
